# Generated by Django 3.2.13 on 2023-01-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('tname', models.CharField(max_length=255, verbose_name='标签')),
                ('short_link', models.CharField(max_length=255, verbose_name='链接')),
                ('view', models.IntegerField(verbose_name='播放次数')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('src', models.CharField(max_length=255, verbose_name='封面')),
                ('danmaku', models.IntegerField(verbose_name='弹幕数')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('share', models.IntegerField(verbose_name='分享数')),
                ('favorite', models.IntegerField(verbose_name='收藏数')),
                ('reply', models.IntegerField(verbose_name='评论数')),
                ('pub_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布地区')),
                ('pubdate', models.DateField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '每周必看',
                'verbose_name_plural': '每周必看',
                'db_table': 'BarData',
            },
        ),
        migrations.CreateModel(
            name='BarsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('tname', models.CharField(max_length=255, verbose_name='标签')),
                ('short_link', models.CharField(max_length=255, verbose_name='链接')),
                ('view', models.IntegerField(verbose_name='播放次数')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('src', models.CharField(max_length=255, verbose_name='封面')),
                ('danmaku', models.IntegerField(verbose_name='弹幕数')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('share', models.IntegerField(verbose_name='分享数')),
                ('favorite', models.IntegerField(verbose_name='收藏数')),
                ('reply', models.IntegerField(verbose_name='评论数')),
                ('pub_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布地区')),
                ('pubdate', models.DateField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '热播排行',
                'verbose_name_plural': '热播排行',
                'db_table': 'BarsData',
            },
        ),
        migrations.CreateModel(
            name='Colect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_title', models.CharField(max_length=255, verbose_name='收藏视频')),
                ('co_down_link', models.CharField(max_length=255, verbose_name='链接')),
                ('co_down_img', models.CharField(max_length=255, verbose_name='封面')),
            ],
            options={
                'verbose_name': '收藏列表',
                'verbose_name_plural': '收藏列表',
                'db_table': 'Colect',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('tname', models.CharField(max_length=255, verbose_name='标签')),
                ('short_link', models.CharField(max_length=255, verbose_name='链接')),
                ('view', models.IntegerField(verbose_name='播放次数')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('src', models.CharField(max_length=255, verbose_name='封面')),
                ('danmaku', models.IntegerField(verbose_name='弹幕数')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('share', models.IntegerField(verbose_name='分享数')),
                ('favorite', models.IntegerField(verbose_name='收藏数')),
                ('reply', models.IntegerField(verbose_name='评论数')),
                ('pub_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布地区')),
                ('pubdate', models.DateField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '历史爬取',
                'verbose_name_plural': '历史爬取',
                'db_table': 'History',
            },
        ),
        migrations.CreateModel(
            name='LintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('tname', models.CharField(max_length=255, verbose_name='标签')),
                ('short_link', models.CharField(max_length=255, verbose_name='链接')),
                ('view', models.IntegerField(verbose_name='播放次数')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('src', models.CharField(max_length=255, verbose_name='封面')),
                ('danmaku', models.IntegerField(verbose_name='弹幕数')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('share', models.IntegerField(verbose_name='分享数')),
                ('favorite', models.IntegerField(verbose_name='收藏数')),
                ('reply', models.IntegerField(verbose_name='评论数')),
                ('pub_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布地区')),
                ('pubdate', models.DateField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '入站必刷',
                'verbose_name_plural': '入站必刷',
                'db_table': 'LintData',
            },
        ),
        migrations.CreateModel(
            name='PieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('tname', models.CharField(max_length=255, verbose_name='标签')),
                ('short_link', models.CharField(max_length=255, verbose_name='链接')),
                ('view', models.IntegerField(verbose_name='播放次数')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('src', models.CharField(max_length=255, verbose_name='封面')),
                ('danmaku', models.IntegerField(verbose_name='弹幕数')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('share', models.IntegerField(verbose_name='分享数')),
                ('favorite', models.IntegerField(verbose_name='收藏数')),
                ('reply', models.IntegerField(verbose_name='评论数')),
                ('pub_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布地区')),
                ('pubdate', models.DateField(blank=True, null=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '综合热门',
                'verbose_name_plural': '综合热门',
                'db_table': 'PieData',
            },
        ),
    ]
